version: "3.8"
services:
  db:
    container_name: quotation-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: jaycon
      POSTGRES_USER: jaycon
      POSTGRES_DB: quotation
    ports:
      - "5432:5432"
    volumes:
      - quotation_db_data:/var/lib/postgresql/data
volumes:
  quotation_db_data: